export const SELECT_ILLNESS = 'SELECT_ILLNESS';
export const FETCH_ILLNESSES = 'FETCH_ILLNESSES';
export const FETCH_HOSPITALS = 'FETCH_HOSPITALS';
export const FETCH_WAITINGLIST = 'FETCH_WAITINGLIST';
